INSERT INTO book(Title, Authors) Values('About a Silence in Literature', 'Živorad Stojković');
INSERT INTO book(Title, Authors) Values('Alice\'s Adventures in Wonderland', 'Lewis Carroll');
INSERT INTO book(Title, Authors) Values('All Quiet on the Western Front', 'Erich Maria Remarque');
INSERT INTO book(Title, Authors) Values('American Psycho', 'Bret Easton Ellis');
INSERT INTO book(Title, Authors) Values('An Area of Darkness', 'V. S. Naipaul');
INSERT INTO book(Title, Authors) Values('The Anarchist Cookbook', 'William Powell');
INSERT INTO book(Title, Authors) Values('Angaray[9]', 'Sajjad Zaheer, Ahmed Ali, Rashid Jahan, and Mahmud-uz-Zafar');
INSERT INTO book(Title, Authors) Values('Animal Farm', 'George Orwell');
INSERT INTO book(Title, Authors) Values('Another Country', 'James Baldwin');
INSERT INTO book(Title, Authors) Values('Apocalypse Culture', 'Adam Parfrey');
INSERT INTO book(Title, Authors) Values('Areopagitica', 'John Milton');
INSERT INTO book(Title, Authors) Values('Bad Samaritans: The Myth of Free Trade and the Secret History of Capitalism', 'Ha-Joon Chang');
INSERT INTO book(Title, Authors) Values('Beijing Coma', 'Ma Jian');
INSERT INTO book(Title, Authors) Values('The Bible', 'see Authorship of the Bible');
INSERT INTO book(Title, Authors) Values('Big River, Big Sea – Untold Stories of 1949', 'Lung Ying-tai');
INSERT INTO book(Title, Authors) Values('Borstal Boy', 'Brendan Behan');
INSERT INTO book(Title, Authors) Values('The Boys', 'Garth Ennis');
INSERT INTO book(Title, Authors) Values('Brave New World', 'Aldous Huxley');
INSERT INTO book(Title, Authors) Values('Burger\'s Daughter', 'Nadine Gordimer');
INSERT INTO book(Title, Authors) Values('By Grand Central Station I Sat Down and Wept', 'Elizabeth Smart');
INSERT INTO book(Title, Authors) Values('Candide', 'Voltaire');
INSERT INTO book(Title, Authors) Values('The Canterbury Tales', 'Geoffrey Chaucer');
INSERT INTO book(Title, Authors) Values('Castration of the Wind', 'Prvoslav Vujčić');
INSERT INTO book(Title, Authors) Values('Catch-22', 'Joseph Heller');
INSERT INTO book(Title, Authors) Values('The Country Girls', 'Edna O\'Brien');
INSERT INTO book(Title, Authors) Values('The Cover-up General', 'Edwin Giltay');
INSERT INTO book(Title, Authors) Values('Curved River', 'Živojin Pavlović');
INSERT INTO book(Title, Authors) Values('The Da Vinci Code', 'Dan Brown');
INSERT INTO book(Title, Authors) Values('The Dark', 'John McGahern');
INSERT INTO book(Title, Authors) Values('The Death of Lorca', 'Ian Gibson');
INSERT INTO book(Title, Authors) Values('The Decameron', 'Giovanni Boccaccio');
INSERT INTO book(Title, Authors) Values('The Devil\'s Discus', 'Rayne Kruger');
INSERT INTO book(Title, Authors) Values('Dictionary of Modern Serbo-Croatian Language', 'Miloš Moskovljević');
INSERT INTO book(Title, Authors) Values('Doctor Zhivago', 'Boris Pasternak');
INSERT INTO book(Title, Authors) Values('Droll Stories', 'Honoré de Balzac');
INSERT INTO book(Title, Authors) Values('Ecstasy and Me', 'Hedy Lamarr');
INSERT INTO book(Title, Authors) Values('Elmer Gantry', 'Sinclair Lewis');
INSERT INTO book(Title, Authors) Values('Fanny Hill or Memoirs of a Woman of Pleasure', 'John Cleland');
INSERT INTO book(Title, Authors) Values('Feast for the Seaweeds', 'Haidar Haidar');
INSERT INTO book(Title, Authors) Values('The Federal Mafia', 'Irwin Schiff');
INSERT INTO book(Title, Authors) Values('Fifty Shades Trilogy', 'E L James');
INSERT INTO book(Title, Authors) Values('Forever Amber (1944)', 'Kathleen Winsor');
INSERT INTO book(Title, Authors) Values('Frankenstein (1818)', 'Mary Shelley');
INSERT INTO book(Title, Authors) Values('The Fugitive (Perburuan) (1950)', 'Pramoedya Ananta Toer');
INSERT INTO book(Title, Authors) Values('The First Circle (1968)', 'Aleksandr Solzhenitsyn');
INSERT INTO book(Title, Authors) Values('The Gods Laugh on Mondays (1995)', 'Reza Khoshnazar');
INSERT INTO book(Title, Authors) Values('The Grapes of Wrath (1939)', 'John Steinbeck');
INSERT INTO book(Title, Authors) Values('Great Soul: Mahatma Gandhi and His Struggle With India (2011)', 'Joseph Lelyveld');
INSERT INTO book(Title, Authors) Values('Green Eggs and Ham', 'Dr. Seuss');
INSERT INTO book(Title, Authors) Values('The Gulag Archipelago (1973)', 'Aleksandr Solzhenitsyn');
INSERT INTO book(Title, Authors) Values('Happy New Year (1975)', 'Rubem Fonseca');
INSERT INTO book(Title, Authors) Values('The Heart of India (1958)', 'Alexander Campbell');
INSERT INTO book(Title, Authors) Values('He Himself (1748)', 'Edward Cangas');
INSERT INTO book(Title, Authors) Values('How to make disposable silencers (1984)', 'Desert and Eliezer Flores');
INSERT INTO book(Title, Authors) Values('Howl (1955)', 'Allen Ginsberg');
INSERT INTO book(Title, Authors) Values('The Hoax of the Twentieth Century', 'Arthur Butz');
INSERT INTO book(Title, Authors) Values('I Didn\'t Do It for You: How the World Betrayed a Small African Nation (2005)', 'Michela Wrong');
INSERT INTO book(Title, Authors) Values('Into the River (2012)', 'Ted Dawe');
INSERT INTO book(Title, Authors) Values('Islam – A Concept of Political World Invasion (2003)', 'R. V. Bhasin');
INSERT INTO book(Title, Authors) Values('July\'s People (1981)', 'Nadine Gordimer');
INSERT INTO book(Title, Authors) Values('Jinnah: India-Partition-Independence (2009)', 'Jaswant Singh');
INSERT INTO book(Title, Authors) Values('Jinnah of Pakistan (1982)', 'Stanley Wolpert');
INSERT INTO book(Title, Authors) Values('Jæger – i krig med eliten (2009)', 'Thomas Rathsack');
INSERT INTO book(Title, Authors) Values('The Jungle (1906)', 'Upton Sinclair');
INSERT INTO book(Title, Authors) Values('The King Never Smiles (2006)', 'Paul M. Handley');
INSERT INTO book(Title, Authors) Values('Lady Chatterley\'s Lover (1928)', 'D. H. Lawrence');
INSERT INTO book(Title, Authors) Values('Lajja (1993)', 'Taslima Nasrin');
INSERT INTO book(Title, Authors) Values('Lethal Marriage', 'Nick Pron');
INSERT INTO book(Title, Authors) Values('Les Moeurs', 'François-Vincent Toussaint');
INSERT INTO book(Title, Authors) Values('Little Black Sambo (1899)', 'Helen Bannerman');
INSERT INTO book(Title, Authors) Values('Lolita (1955)', 'Vladimir Nabokov');
INSERT INTO book(Title, Authors) Values('The Lonely Girl (1962)', 'Edna O\'Brien');
INSERT INTO book(Title, Authors) Values('Lord Horror (1990)', 'David Britton');
INSERT INTO book(Title, Authors) Values('The Lottery (1948)', 'Shirley Jackson');
INSERT INTO book(Title, Authors) Values('Love Comes Later (2014)', 'Mohanalakshmi Rajakumar');
INSERT INTO book(Title, Authors) Values('Lysistrata (411 BC)', 'Aristophanes');
INSERT INTO book(Title, Authors) Values('Madame Bovary (1856)', 'Gustave Flaubert');
INSERT INTO book(Title, Authors) Values('The Man Who Wouldn\'t Stand Up (2012)', 'Jacob M. Appel');
INSERT INTO book(Title, Authors) Values('The Mask of Sanity (2017)', 'Jacob M. Appel');
INSERT INTO book(Title, Authors) Values('Mein Kampf (1925)', 'Adolf Hitler');
INSERT INTO book(Title, Authors) Values('Memoirs of Hecate County (1946)', 'Edmund Wilson');
INSERT INTO book(Title, Authors) Values('The Meritorious Price of Our Redemption (1650)', 'William Pynchon');
INSERT INTO book(Title, Authors) Values('A Message to Man and Humanity', 'Aleksandar Cvetković');
INSERT INTO book(Title, Authors) Values('Mirror of the Polish Crown (1618)', 'Sebastian Miczyński');
INSERT INTO book(Title, Authors) Values('Moll Flanders or The Fortunes and Misfortunes of the Famous Moll Flanders (1722)', 'Daniel Defoe');
INSERT INTO book(Title, Authors) Values('The Mountain Wreath (1847)', 'Petar II Petrović-Njegoš');
INSERT INTO book(Title, Authors) Values('My Father\'s Daughter (2005)', 'Hannah Pool');
INSERT INTO book(Title, Authors) Values('My Watch (2005)', 'Olusegun Obasanjo');
INSERT INTO book(Title, Authors) Values('Naked Lunch (1959)', 'William S. Burroughs');
INSERT INTO book(Title, Authors) Values('Naree (1992)', 'Humayun Azad');
INSERT INTO book(Title, Authors) Values('New Class (1957)', 'Milovan Đilas');
INSERT INTO book(Title, Authors) Values('Nineteen Eighty-Four (1949)', 'George Orwell');
INSERT INTO book(Title, Authors) Values('fr:Noir Canada (2008)', 'Alain Deneault');
INSERT INTO book(Title, Authors) Values('Notre ami le roi (1993)', 'Gilles Perrault');
INSERT INTO book(Title, Authors) Values('Nine Hours To Rama (1962)', 'Stanley Wolpert');
INSERT INTO book(Title, Authors) Values('The Naked and the Dead (1948)', 'Norman Mailer');
INSERT INTO book(Title, Authors) Values('On Fierce Wound – Fierce Herb', 'Ratko Zakić');
INSERT INTO book(Title, Authors) Values('One Day of Life (1980)', 'Manlio Argueta');
INSERT INTO book(Title, Authors) Values('One Day in the Life of Ivan Denisovich (1962)', 'Alexander Solzhenitsyn');
INSERT INTO book(Title, Authors) Values('Onward Muslim Soldiers', 'Robert Spencer (author)');
INSERT INTO book(Title, Authors) Values('The 120 Days of Sodom (1789)', 'Marquis de Sade');
INSERT INTO book(Title, Authors) Values('Operation Dark Heart (2010)', 'Army Reserve Lt. Col. Anthony Shaffer');
INSERT INTO book(Title, Authors) Values('The Peaceful Pill Handbook (2007)', 'Philip Nitschke and Fiona Stewart');
INSERT INTO book(Title, Authors) Values('Persepolis (2000)', 'Marjane Satrapi');
INSERT INTO book(Title, Authors) Values('Peyton Place (1956)', 'Grace Metalious');
INSERT INTO book(Title, Authors) Values('The Protocols of the Elders of Zion (1903)', 'Unknown');
INSERT INTO book(Title, Authors) Values('Përbindëshi (The Monster) (1965)', 'Ismail Kadare');
INSERT INTO book(Title, Authors) Values('The Quran', 'Muslim');
INSERT INTO book(Title, Authors) Values('Rangila Rasul (1927)', 'Pt. Chamupati');
INSERT INTO book(Title, Authors) Values('Rights of Man (1791)', 'Thomas Paine');
INSERT INTO book(Title, Authors) Values('Rowena Goes Too Far (1931)', 'H. C. Asterley');
INSERT INTO book(Title, Authors) Values('The Satanic Verses (1988)', 'Salman Rushdie');
INSERT INTO book(Title, Authors) Values('The Satanic Bible (1969)', 'Anton LaVey');
INSERT INTO book(Title, Authors) Values('Schindler\'s Ark (1982)', 'Thomas Keneally');
INSERT INTO book(Title, Authors) Values('Scouting for the Reaper (2014)', 'Jacob M. Appel');
INSERT INTO book(Title, Authors) Values('El Señor Presidente', 'Miguel Ángel Asturias');
INSERT INTO book(Title, Authors) Values('Sexual Customs ("Xing Fengsu") (1989)', '.');
INSERT INTO book(Title, Authors) Values('Shivaji – Hindu King in Islamic India (2003)', 'James Laine');
INSERT INTO book(Title, Authors) Values('Smash and Grab: Annexation of Sikkim (1984)', 'Sunanda K. Datta-Ray');
INSERT INTO book(Title, Authors) Values('A Sneaking Suspicion (1995)', 'John Dickson');
INSERT INTO book(Title, Authors) Values('Snorri the Seal (1941)', 'Frithjof Sælen');
INSERT INTO book(Title, Authors) Values('Soft Target: How the Indian Intelligence Service Penetrated Canada (1989)', 'Zuhair Kashmeri & Brian McAndrew');
INSERT INTO book(Title, Authors) Values('Sophie\'s Choice (1979)', 'William Styron');
INSERT INTO book(Title, Authors) Values('A Spoon on Earth', 'Hyeon Gi-yeong');
INSERT INTO book(Title, Authors) Values('Spycatcher (1985)', 'Peter Wright');
INSERT INTO book(Title, Authors) Values('Storytellers II', 'Boško Novaković');
INSERT INTO book(Title, Authors) Values('The Stud (1969)', 'Jackie Collins');
INSERT INTO book(Title, Authors) Values('Suicide mode d\'emploi (1982)', 'Claude Guillon');
INSERT INTO book(Title, Authors) Values('Thalia', 'Arius (AD 250 or 256 – 336)');
INSERT INTO book(Title, Authors) Values('Thoughts of a Corpse', 'Prvoslav Vujčić');
INSERT INTO book(Title, Authors) Values('Tropic of Cancer (1934)', 'Henry Miller');
INSERT INTO book(Title, Authors) Values('The True Furqan (1999)', '"Al Saffee" and "Al Mahdee"');
INSERT INTO book(Title, Authors) Values('The Truth About Muhammad', 'Robert Spencer');
INSERT INTO book(Title, Authors) Values('Uitgeverij Guggenheimer ("Publisher Guggenheimer") (1999)', 'Herman Brusselmans');
INSERT INTO book(Title, Authors) Values('Ulysses (1922)', 'James Joyce');
INSERT INTO book(Title, Authors) Values('Uncle Tom\'s Cabin (1852)', 'Harriet Beecher Stowe');
INSERT INTO book(Title, Authors) Values('Understanding Islam through Hadis (1982)', 'Ram Swarup');
INSERT INTO book(Title, Authors) Values('United States – Vietnam Relations, 1945–1967: A Study Prepared by the Department of Defense (1971)', 'Robert McNamara and the United States Department of Defense');
INSERT INTO book(Title, Authors) Values('Unarmed Victory (1963)', 'Bertrand Russell');
INSERT INTO book(Title, Authors) Values('Various works', 'Shen Congwen');
INSERT INTO book(Title, Authors) Values('Truth for Germany—The Question of Guilt for the Second World War', 'Udo Walendy');
INSERT INTO book(Title, Authors) Values('The Well of Loneliness (1928)', 'Radclyffe Hall');
INSERT INTO book(Title, Authors) Values('White Niggers of America (1970)', 'Pierre Vallières');
INSERT INTO book(Title, Authors) Values('Wild Swans (1993)', 'Jung Chang');
INSERT INTO book(Title, Authors) Values('The World Is Full of Married Men (1968)', 'Jackie Collins');
INSERT INTO book(Title, Authors) Values('Year 501: The Conquest Continues (1993)', 'Noam Chomsky');
INSERT INTO book(Title, Authors) Values('You: An Introduction (2008)', 'Michael Jensen');
INSERT INTO book(Title, Authors) Values('Zhuan Falun (1993)', 'Li Hongzhi');